### ISSUE TITLE
translation enhancements

### ISSUE THREAD

**Issue by shikulja** [Sulpitz/QuickHeal#12]
1. add use buble spell 
instead of manual spell translation
BS[SPELL NAME]  
and delete the unused loc lines in the xml and files
2. add Translation folder
add
 QuickHeal.lua QuickHeal.xml QuickHeal*class*.lua 
translation lines with ace locale
3. add translation En to the localization folder

**Comment by Sulpitz** [comment]
Hey,
I'm adding you as a collaborator, so you can make the changes you propose by yourself.
With classic coming closer, I will not do anything more with the add-on.
Feel free to make the changes you see fit.
kind regards

**Comment by shikulja** [comment]
> Hey,
> I'm adding you as a collaborator, so you can make the changes you propose by yourself.
> With classic coming closer, I will not do anything more with the add-on.
> Feel free to make the changes you see fit.
> kind regards

Thanks, my knowledge and strength, was only enough to change the code, with the possibility of a normal translation.
Perhaps I will only add minor translation fixes. In its current form is quite satisfied.

**Comment by Sulpitz** [comment]
Fair enough!
