### ISSUE TITLE
Can you get this working in the Classic Retail WoW release?

### ISSUE THREAD

**Issue by icecom3** [Sulpitz/QuickHeal#15]
I can't get this working in the new classic release of retail.  I was using in private vanilla, works there, but in retail classic it does not load.  I can't live without this addon.

**Comment by shikulja** [comment]
> I can't get this working in the new classic release of retail. I was using in private vanilla, works there, but in retail classic it does not load. I can't live without this addon.

I totally agree with you.
Sorry for wow classic api lua changed
therefore, it will not work.
Need to create a separate branch and port the addon.
I hope the popularity of wow classic will attract more developers

**Comment by Sulpitz** [comment]
There is no use in porting this addon, because the the API will not allow this addon to work like it used to in vanilla.
We have to come up with something else.
