### ISSUE TITLE
[Discussion] Functions and things that could be implemented

### ISSUE THREAD

**Issue by shikulja** [Sulpitz/QuickHeal#18]
1. https://gitlab.com/AMGarkin/SmartHealer 
uses HealComm or TheoryCraft for auto rank
one could add something similar, this could improve the accuracy of lowering the rank

2. detect luaunlock and use locked functions
it would be possible to automatically cancel the action when overheal threshold, as well as use the healing with the pressed button, without spamming the keyboard

3.  rewrite gui, on lua (ace2\waterfall), we will have a more accurate look, and the code.

4. update clickcast(quickclick) for compatibility with pfui, LunaUF

**Comment by Sulpitz** [comment]
Hi Shikulja,
Quickheal should already do what SmartHealer is doing.
Heals are automatically lowered to the appropriate rang to top the player with an amount of overhealing specified by a hardcoded multiplier.
From my experience the downranking worked quite well.
It does detect if the heal being cast will overheal the target and will cancel it. I'm not sure though, if it also cancels if there is predicted heal landing before the heal being cast.
But of course feel free to experiment. I just wanted to add what I remembered.

**Comment by shikulja** [comment]
@Sulpitz hello, good to see you)

- I just suggested using TheoryCraft as an alternative healcomm and current downrank calculation algorithm, and see an example in SmartHealer

- Yes, he can predict and cancel (switch the target) before the cast, but he can’t cancel the current cast already, when someone used healing on the target earlier, during the character’s cast

- a small error was also found.
other players do not see castes of healing, because the “target” is not chosen “directly”, or this healcomm-or-translation error, I still have not verified it completely.

(the second and third problems are adjusted to each other)
