### ISSUE TITLE
Add line of sight blacklist to HoTs

### ISSUE THREAD

**Issue by SoggyDiaper** [Sulpitz/QuickHeal#23]
The line of sight blacklist function works well for heals with a cast time, but there is no blacklist functionality for HoTs at all.

I can be spamming "/qh hot", only for it to get stuck continually trying to heal the same target who is hiding behind a tree, and I end up not using a HoT at all.

Would it be possible for the LoS blacklist functionality to be added to HoTs as well as regular heals?

**Comment by shikulja** [comment]
@SoggyDiaper 
This version of QH does not support hots casting.
Contact the author of your version of QH
The error is simple, I think it can be fixed
