### ISSUE TITLE
Add power word (shield) in the list of spells

### ISSUE THREAD

**Issue by knasen88** [Sulpitz/QuickHeal#3]
Hi, I would like to ask if it's possible for you to add (for priests) when somebody is considered at critical health (lets say <25%) that instead of launching a Flash Heal, it casts a priest shield instead. 
As an option maybe /qh healshield (same as others + shield if critical)
Would it also be possible to make one purely for shields? /qh shield and it casts on the lowest member that currently does not have weakened soul debuff.
You may close this when you read it as it's not really an issue just a suggestion/request

**Comment by Sulpitz** [comment]
Thats a good Idea. I was also thinking about BoP for Pallys. I will work on this when i find time.
