### ISSUE TITLE
Error stops addon

### ISSUE THREAD

**Issue by josephtrove** [Sulpitz/QuickHeal#4]
With the latest versions of QuickHeal, QCspy, Luna, and BonusScanner all installed, I sometimes get an error when using /qh, "Interface\AddOns\QuickHeal\QuickHealPriest.lua:135: attempt to compare a number with nil", at which point the healing bar gets stuck on my screen halfway through a heal with the "Healing Target" text on it, and the addon stops working.

**Comment by Sulpitz** [comment]
I will look into that. What is QCspy?

**Comment by Sulpitz** [comment]
I could not reproduce the error. Maybe wait for a new version and report back if the error still happens. Maybe you can tell me more then.
