### ISSUE TITLE
Command for swapping Max Rank?

### ISSUE THREAD

**Issue by Jokelas1** [Sulpitz/QuickHeal#6]
When playing a druid sometimes I want to use every single rank in my disposal Healing Touch ranks 1 through 11. But, very often the damage becomes a bit lower and utilizing 3s cast times is just not viable so I want to swap down to only using rank 3 or 4 in the middle of a fight. Doing this with a macro would be an amazing help.

eg. /qh maxrank 4
      /qh maxrank 11
      /qh maxrank 7

etc

Thanks in advance.

**Comment by josephtrove** [comment]
That would be a sick feature.

**Comment by Sulpitz** [comment]
I'm playing a Priest as main and Pally as alt. If you log in on a priest and do /qh downrank, you will find a window that lets you pick the max rank that you want to use. I'm working on getting that feature in for Pally, but i don't have a Druid to test it on. I will try to do it eventually.
